### ISSUE TITLE
Booklet template gets changed after upgrade to 2.x

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#111]
Here is the before (1.10.1):

[current_meeting_list_9820194045022.pdf](https://github.com/bmlt-enabled/bread/files/3587804/current_meeting_list_9820194045022.pdf)

Here is the after (2.1.1)

[current_meeting_list_9820194045418.pdf](https://github.com/bmlt-enabled/bread/files/3587806/current_meeting_list_9820194045418.pdf)

**Comment by californiasteve** [comment]
I'm seeing the same thing with all of my websites. I have a few that have expanded to a new page breaking the look.

**Comment by otrok7** [comment]
The page sizes are also different... in 1.10 the page sage 279,4x197.2...  in 2.1 the page size is letter.

**Comment by otrok7** [comment]
Can one of you send me an export from one of the problematic settings?

**Comment by pjaudiomv** [comment]
[south-coastal-area-of-narcotics-anonymous-meeting-list-settings-09-08-2019.json.txt](https://github.com/bmlt-enabled/bread/files/3588008/south-coastal-area-of-narcotics-anonymous-meeting-list-settings-09-08-2019.json.txt)

had to append .txt because git doesnt allow you to attahc json files

**Comment by radius314** [comment]
Also there is link on this ticket.  https://github.com/bmlt-enabled/bread/issues/109

**Comment by otrok7** [comment]
fixed in 2.1.2

**Comment by radius314** [comment]
I have tested this and it looks good.  Thanks.
