### ISSUE TITLE
Headers Not Continuing to Next Column

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bread#112]
I'm doing a demo and I changed the formats and font sizes and the headers didn't continue onto the top of each column. 

[bmlt-southeastfamilyarea09-14-2019.json.zip](https://github.com/bmlt-enabled/bread/files/3612961/bmlt-southeastfamilyarea09-14-2019.json.zip)

[current_meeting_list_91420195050403.pdf](https://github.com/bmlt-enabled/bread/files/3612963/current_meeting_list_91420195050403.pdf)

**Comment by tempsaint** [comment]
Oops... my bad. I missed the Continuation Header check box. Maybe that should be on by default?

**Comment by californiasteve** [comment]
You can change line-height also and that will usually fix it.

**Comment by otrok7** [comment]
Before 2.1 you could play with page_height_adjust, or line_height, and that would have an influence on the continuation headers... or not.  Sometimes adding a new meeting messed things up enough that you would get some headers, and some not.  Or maybe the meeting was squeezed on with smaller font... and then you could play with the page height again... that's all gone now... The flag is set or it isn't and you get headers or you don't.  But the old behavior is hard to emulate or to upgrade to the new system.  During upgrade to 2.1, the system guesses about what the user wants based on the font size, line height, and page_height_adjust.  Sometimes it guesses wrong.
