### ISSUE TITLE
Bread process loop

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bread#122]
there seems to be some sort of process loop or somehting, similar to what sierra sage i belive had. My website got hit over a million times to same endpoint by bread. attaching access logs. this almost brought down my website, had to downgrade.

[sslaccesslog_nerna.nercna.org_11_9_2019(1).gz](https://github.com/bmlt-enabled/bread/files/3827563/sslaccesslog_nerna.nercna.org_11_9_2019.1.gz)

**Comment by pjaudiomv** [comment]
I have figured out the issue, there are two problems. 
1. with the latest version of root server GetServerInfo will return `fa` for farsi as a lang, but there was no db migration done so the formats don't exist in the server.
2. bread should have better error handling instead of continuing to hit GetServerInfo. the lang exists in GetServerInfo but no formats do so it keeps retrying.

**Comment by pjaudiomv** [comment]
this theory is def not 100% correct but something with ading farsi to root server caused this

**Comment by otrok7** [comment]
Well, one thing that is wrong is that it gets the plugins construct method (indirectly) makes the call, regardless if bread is just loading or actually going to do something.

**Comment by otrok7** [comment]
I am looking into the Farsi problem, but I only load the formats in the "weekday_language" and the "asm_language"...  at least I think that's all I load.  But I generated a beta that is more careful about making remote calls... can you test?

**Comment by otrok7** [comment]
Do I understand correctly, bread was running OK, then you updated the root server, and then it blew up?

**Comment by pjaudiomv** [comment]
yes....yes thats correct.

**Comment by pjaudiomv** [comment]
ill check the beta

**Comment by otrok7** [comment]
Did the beta help?

**Comment by pjaudiomv** [comment]
Yes it did, I don't know how but it did. Thank you so much.
