### ISSUE TITLE
Ability to place non meetings content on meetings page (ie. meeting legend?)

### ISSUE THREAD

**Issue by nonsub** [bmlt-enabled/bread#131]
Hope this makes sense. At lease in tri-fold. If there is room then I wish there was a way to add the meeting format legend to the same page the meetings get printed on so the reader does not have to flip over to try and decipher format codes. Thanks!

**Comment by pjaudiomv** [comment]
There is I think in the extra content area you just don't put a new page in. I can check what the setting is when I get home.

**Comment by nonsub** [comment]
Hi pjaudiomv! Duhhhhhh @ self. I just had to remove [new_column] !

Thanks!

**Comment by pjaudiomv** [comment]
Yes that's it, no problem.
