### ISSUE TITLE
Google Maps API Key for BMLT

### ISSUE THREAD

**Issue by DanielWright98** [bmlt-enabled/bread#136]
Is there a work-around for creating a billing account in order to get the API key for Google Maps?
I really don't want to give them a credit card number. I'm also not sure about what they'll be billing me for.

**Comment by pjaudiomv** [comment]
bread does not need or require a google api key.

**Comment by pjaudiomv** [comment]
for the other bmlt plugins, there is not currently a work around. You will not end up getting billed for anything as the limit is something like 100,000 requests a day. they want it just in case you go over it (you won't). there is a ticket open for the root server to use open street maps which does not require an api key.

**Comment by pjaudiomv** [comment]
the following wordpress plugins also do not require an api key

https://wordpress.org/plugins/bmlt-meeting-map/
https://wordpress.org/plugins/bmlt-tabbed-map/

**Comment by DanielWright98** [comment]
Thank you.
And sorry, I should not have posted this under Bread.

**Comment by pjaudiomv** [comment]
no worries. :)
