### ISSUE TITLE
BMLT Map

### ISSUE THREAD

**Issue by DanielWright98** [bmlt-enabled/bread#137]
So my understanding is that since Google now "enforces HTTPS" and the root server I'm dealing with is http://naflorida.org/bmlt_server our map function will not work.
Am I correct in that?

**Comment by pjaudiomv** [comment]
Use https://naflorida.org/bmlt_server/

**Comment by DanielWright98** [comment]
OK. Thanks.

**Comment by pjaudiomv** [comment]
👍
