### ISSUE TITLE
Virtual Meetings

### ISSUE THREAD

**Issue by DanielWright98** [bmlt-enabled/bread#146]
Link and phone number for virtual meetings are displaying on my online meeting schedule, but not with the meeting list generated by Bread.
Any help with this?

**Comment by californiasteve** [comment]
On the "BMLT Server" tab you have to check the "Allow any site-defined fields to be used in meeting templates" check box. Then go to your "meetings" tab and insert from the "meeting template fields" dropdown in the "meeting information" at the bottom are the three ways of displaying the links for virtual meetings, qr codes or phone numbers.

**Comment by DanielWright98** [comment]
That works. Thank you. I've been bumping around on that for a couple of days. I really appreciate your help.
