### ISSUE TITLE
Virtual Meeting Information Not Populating

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/bread#149]
Bread Version 2.4.3

Sites where this happens
[https://centralindianana.org/](https://centralindianana.org/)
[https://michigan-na.org](https://michigan-na.org)
[https://refactory.com/?current-meeting-list=1](https://refactory.com/?current-meeting-list=1) (test site)

When using the virtual meeting information options under Meeting Template Fields > Meeting Information string literals are generated for the printed list. Is there any plan to print the data? If not can they be removed so they don't cause confusion?

- virtual_meeting_link
- phone_meeting_number
- [QRCode code="virtual_meeting_link" size="0.8"]

**Comment by otrok7** [comment]
Sorry for the late response, I was on vacation---  is the  
"Allow any site-defined fields to be used in meeting templates" checkbox in the "BMLT Server" page selected?

**Comment by alanborning** [comment]
I ran across the same issue.  Checking the box as you suggested fixed the problem. But is this still a bug (either a garden-variety bug or a usability bug)? Those fields were there in the "Meeting Template Fields" menu without the box checked -- it seems like  they should not appear in the menu if they won't work.

**Comment by klgrimley** [comment]
No worries. That was not checked. After checking I'm no longer getting any of the meetings with the VM or HY field showing on the generated pdf.

**Comment by klgrimley** [comment]
If it helps. Here's the link to our BMLT server [https://centralindianana.org/main_server](https://centralindianana.org/main_server)

**Comment by klgrimley** [comment]
We're using a custom query on the BMLT Server tab ( &formats=-60 ) to exclude TC meetings. On the Meetings tab under the Additional List section I'm also having to set "Format of meetings in the additional list:" to Virtual Meetings to not get a white screen. I'm assuming there's a php error but haven't had a chance to check.

**Comment by otrok7** [comment]
I fixed some bugs in the latest release, let me check using my server.  Please do an export (on the configuration page) and send me the generated JSON file.  Use Slack to do the send, or just post it here.

**Comment by klgrimley** [comment]
`{"root_server":"https:\/\/centralindianana.org\/main_server","service_body_1":"Central Indiana Area,1,0,Parent ID","service_body_2":"Not Used","service_body_3":"Not Used","header_font_size":7.5,"area_service_meetings":null,"front_page_content":"<p style=\"text-align: center\">\u00a0<\/p>\r\n<p>&nbsp;<\/p>\r\n<p style=\"text-align: center\"><img class=\"aligncenter wp-image-455\" src=\"https:\/\/centralindianana.org\/wp-content\/uploads\/2016\/04\/cropped-CIANA-hug-circle-300x300.jpg\" alt=\"cropped-CIANA-hug-circle.jpg\" width=\"200\" height=\"200\" \/><\/p>\r\n<p>&nbsp;<\/p>\r\n<p>&nbsp;<\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 15pt\"><strong>[service_body_1]<\/strong><\/span><\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 15pt\"><strong>MEETING\u00a0DIRECTORY<\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 20px\"><b>July 2020\u00a0<\/b><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 14pt\"><b>24 HOUR HELPLINE<\/b><\/span><\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 14pt\"><strong>(317) 875-5459<\/strong><\/span><\/p>\r\n<p style=\"text-align: center\">\u00a0<\/p>\r\n<p class=\"p1\" style=\"text-align: center\">Including:<\/p>\r\n<p class=\"p1\" style=\"text-align: center\">Avon, Brownsburg, Camby, Carmel, Cicero, Clermont, Danville, Fishers, Franklin, Greenfield, Greenwood, Indianapolis, Martinsville, Noblesville, Plainfield, Rushville, Shelbyville, Zionsville<\/p>\r\n<p class=\"p1\" style=\"text-align: center\">\u00a0<\/p>\r\n<p class=\"p1\" style=\"text-align: center\">NA is a nonprofit fellowship or society of men and women for\u00a0whom drugs had become a major problem. We are recovering\u00a0addicts who meet regularly to help each other stay clean. NA is\u00a0not affiliated with any of the facilities where our meetings are\u00a0held.<\/p>\r\n<p style=\"text-align: center\">\u00a0<\/p>\r\n<p style=\"text-align: center\"><b><\/b><span style=\"font-size: 10pt\"><b>Central Indiana Area of <\/b><\/span><\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 10pt\"><b>Narcotics Anonymous<\/b><\/span><\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 10pt\"><strong>PO Box 1011<\/strong><\/span><\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 10pt\"><strong>Indianapolis, IN 46206-1011<\/strong><\/span><\/p>\r\n<p style=\"text-align: center\">\u00a0<\/p>\r\n<p style=\"text-align: center\"><span style=\"font-size: 12pt\"><strong>https:\/\/centralindianana.org<\/strong><\/span><\/p>\r\n<p style=\"text-align: center\">\u00a0<\/p>\r\n<p style=\"text-align: center\">\u00a0<\/p>\r\n<p style=\"text-align: center\">\u00a0<\/p>","front_line_height":"1.0","area_service_meetings_line_height":null,"content_font_size":7.29999999999999982236431605997495353221893310546875,"content_line_height":1.1999999999999999555910790149937383830547332763671875,"front_page_font_size":10,"helpines":"Bahamas, 242-426-5245\r\nBay Area\/Pinellas (Pinellas County), 727-547-0444\r\nBoca Raton\/Delray Beach, 561-393-0303\r\nBradenton, 941-957-7910\r\nDaytona Beach (Volusia County), 800-206-0731\r\nFirst Coast Area (Duval County), 904-723-5683\r\nForest\/Ocala (Marion City), 352-368-6061\r\nGainesville (Uncoast Area), 352-376-8008\r\nJacksonville, 800-576-4357\r\nHeartland Area (Lakeland\/Polk County), 863-683-0630\r\nMelbourne\/Titusville, 321-631-4357\r\nNature Coast, 352-508-1604\r\nNew Port Richey\/Zephrhills, 800-691-5551\r\nNorth-West Florida, 800-467-7314\r\nPalm Coast Area, 561-848-6262\r\nRecover Coast Area (Pasco County), 727-842-2433\r\nRiver Coast Area (Hernando County), 352-754-7200\r\nSuncoast Area (Sarasota), 941-257-5055\r\nSouth Florida Region, 866-288-6262\r\nSpace Coast Area (Brevard County), 321-631-4357\r\nSt- Petersburg\/Clearwater\/Pinellas County, 727-547-0444\r\nTallahassee\/Big Bend, 850-224-2321\r\nTampa (Hillsborough County), 813-879-4357\r\nTreasure Coast (St- Lucie County), 888-624-6822\r\nUnity Springs (West Volusia County), 888-385-3121","helpines_line_height":null,"helpline_line_height":"1.5","helplines_line_height":null,"helplines":null,"last_page_content":"","front_page_line_height":"1.0","last_page_line_height":1,"page_layout":null,"service_body_4":"Not Used","service_body_5":"Not Used","time_option":1,"remove_space":true,"helplines_font_size":null,"format_codes":null,"format_codes_font_size":null,"format_codes_line_height":null,"page_size":"legal","page_fold":"quad","meeting_sort":"day","cache_time":0,"include_zip":false,"page_orientation":"L","show_status":null,"use_custom_section":null,"custom_section_content":"<p>&nbsp;<\/p>\r\n<table style=\"width: 100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 2pt;text-align: center;background-color: #000000\"><span style=\"font-size: 7pt\"><strong><span style=\"color: #fff\">MEETING FORMAT LEGEND<\/span><\/strong><\/span><\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>[format_codes_used_basic]<\/p>\r\n<p><strong>* Meetings with a VM format may not be meeting in person. *<\/strong><\/p>\r\n<p>[new_column]<\/p>\r\n<table style=\"width: 100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 2pt;text-align: center;background-color: #000000\"><span style=\"font-size: 7pt\"><strong><span style=\"color: #fff\">PHONE NUMBERS<\/span><\/strong><\/span><\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p style=\"line-height: 1.3;margin-top: 5px\"><span style=\"font-size: 11pt\">For:__________________________________________<\/span><br \/><span style=\"font-size: 11pt\">_______Males only \u00a0 _______Females only<\/span><br \/><span style=\"font-size: 11pt\"> Remember, don\u2019t use, call us instead. <br \/>WE CARE!!<\/span><\/p>\r\n<table style=\"width: 100%\" cellspacing=\"10\" cellpadding=\"5\">\r\n<tbody>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<tr>\r\n<td style=\"border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #111111\">\u00a0<\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>[new_column]<\/p>","custom_section_line_height":1,"area_service_meetings_font_size":null,"which_format_codes":null,"meeting_template":"","custom_section_font_size":6.5,"include_meeting_email":false,"bmlt_login_id":"","bmlt_login_password":"","last_page_font_size":10,"column_line":false,"used_format_1":"","used_format_2":"","time_clock":"12","page_height":"200","column_gap":10,"margin_right":2,"margin_left":2,"margin_bottom":2,"margin_top":2,"meeting_template_content":"<table style=\"margin-top: 0px;width: 100%;padding: 0px\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #dddddd;vertical-align: top;text-align: left\"><span style=\"font-family: courier\"><strong>time<\/strong><\/span><br \/><span style=\"font-family: courier;font-size: 6pt\">hrs hr(s)<\/span><\/td>\r\n<td style=\"width: 2pt;border-bottom-width: 1px;border-bottom-style: solid;border-bottom-color: #dddddd;vertical-align: top;text-align: center\">\u00a0<\/td>\r\n<td style=\"border-bottom: 1px solid #dddddd;vertical-align: top\">\r\n<p><strong>group<\/strong>, <em>(borough)<\/em>, location,\u00a0info,\u00a0street, city, state, zip <strong>(formats)<\/strong>\u00a0<em>comments<\/em><\/p>\r\n<\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>","col_color":"#274fae","header_text_color":"#ffffff","header_background_color":"#000000","header_uppercase":1,"header_bold":1,"include_asm":false,"weekday_language":"en_es","borough_suffix":"Borough","county_suffix":"County","include_protection":false,"protection_password":"","extra_meetings":"","sub_header_shown":"display","custom_query":"&formats=-60","recurse_service_bodies":0,"base_font":"dejavusanscondensed","neighborhood_suffix":"Neighborhood","city_suffix":"City","pagenumbering_font_size":9,"extra_meetings_enabled":0,"weekday_start":"1","pageheader_fontsize":7.5,"suppress_heading":0,"pageheader_textcolor":"#000000","pageheader_backgroundcolor":"#ffffff","booklet_pages":false,"asm_template_content":"","retrieve_all_fields":0,"asm_format_key":"@Virtual@","asm_sort_order":"same","asm_logged_in":false,"bread_version":"2.0","margin_header":0,"pageheader_content":"","watermark":"","authors":[1],"colorspace":"0","asm_language":"","cont_header_shown":1,"main_grouping":"day","subgrouping":"","user_agent":"","asm_custom_query":""}`

**Comment by otrok7** [comment]
Hi, when you select a format for the "additional list" you are (by default) out that format from the main list.  But, unlike the main meeting list, Bread needs to know where to put the additional list.  You do this by adding [additional_meetings] into your custom content.  And then, in the format for the additional meetings you can use the virtual_meeting_link , etc, fields. 

Hope that is clear!

new version was released today, please update

**Comment by klgrimley** [comment]
Yes, but I'm not really wanting to us the "additional list" it's just currently set to avoid getting a white screen when trying to generate the pdf.

I've updated to today's release.

**Comment by otrok7** [comment]
Ah, that's the sort of thing you should include in your bug report ;-).  Fix on the way.

**Comment by klgrimley** [comment]
Doesn't look like 2.5.2 has pushed out to the plugin directory. If it's not there by the time I'm done with work I'll just pull it directly from here.

**Comment by otrok7** [comment]
i've pretty much have forgotten how to use wordpress directory... at least when I'm not focused.... the git version should work but I'm bumping the wordpress version, too.   At least, I'm trying.

**Comment by otrok7** [comment]
OK, WP Directory is updated.  Give it a try, at let me know.

**Comment by klgrimley** [comment]
Working as expected now. However I do agree with Alan's comment. Should we close this one and start a different issue for that?
