### ISSUE TITLE
Additional list is not pulling correct information

### ISSUE THREAD

**Issue by Hal0smom** [bmlt-enabled/bread#151]
My additional list is set to pull only Virtual Meetings and is now pulling all meetings with a virtual link entered in the BMLT.

**Comment by otrok7** [comment]
Question:  Does VirtualMeeting appear twice in the list of possible formats by which to filter the addition list?  And, if so, have you selected the top one?

**Comment by tempsaint** [comment]
I might have another comment for this... I created meeting lists and chose to display the Virtual Meetings in the Additional List section. bread correctly then shows only the in-person meetings in the Main List and the virtual meetings in the Additional List. But, the HYbrid meetings are only being displayed in the Additional List. They should be displayed in both the Main list and the Additional List.

**Comment by tempsaint** [comment]
I did see the earlier comment and changed the setting for the additional list from Virtual Meetings to Virtual Meeting (further down the list). However, now the Hybrid meetings only appear in the Main list and not in the Additional List.

**Comment by otrok7** [comment]
Please send me the json file generated when you export this list (from the configuration tab)

**Comment by tempsaint** [comment]
Here's the json file (zipped because github wouldn't allow the json). 
I am using your grouping extension for this and grouping two counties into the list and excluding the other 7 counties in our state.

[hartford-tolland-counties12-08-2020.json.zip](https://github.com/bmlt-enabled/bread/files/5659600/hartford-tolland-counties12-08-2020.json.zip)

**Comment by otrok7** [comment]
Please test against 2.5.6 beta 2:  https://github.com/bmlt-enabled/bread/releases/download/2.5.6-beta2/bread.zip

**Comment by tempsaint** [comment]
Hi Ron, 2.5.6. beta 2 did NOT fix the issue. The Hybrid meeting are still only appearing once instead of in both the Main list and the Additional List (of Virtual Meeting)

**Comment by tempsaint** [comment]
2.5.6 Beta 3 fixed the issue for me.
