### ISSUE TITLE
about older bread version with template

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/bread#152]
... there was in an older version of Bread the possibility of keep a defaul layout and pages configuration. Here in Brazil we need to configure a LOT of meetings lists... for example, we have here 9 regions and around 152 areas....  it is a lot of job.... we want to create a meeating list per area... and it is eazy, but if some service structure tell us to change something we will need to do it 152 times... in case if we are using a default template we just need to change this template.. what do you guys can say?
Our idea is to create a template just for front page, for example... when we change this template all configurations using this template assume it

**Comment by otrok7** [comment]
Unfortunately, templates in Bread don't work that way.  They are a starting point that you can modify, there's no connection back to the original template.  

Are the meeting lists multiple configurations on the same server?  ?current-meetinglist=1,2,3 etc.  That has to be the starting point.  Next question is: how much do the meetinglists differ?  I can imagine having a base meetinglist configuration and then having it applied to a set of service bodies.  With front-page template, meeting template, etc exactly the same, only difference is the service body being used.  To define a new meeting list, you set the service body, and say which configuration you want to use. Is that something that would work for you?

**Comment by radius314** [comment]
There is a way to parameterize bread templates by passing querystring values.  Not sure if that is useful.

**Comment by abna-brasil** [comment]
@otrok7 .... yep, we have here multiple configurations for all of our service body (area service commitee), and we are not sure about the png logo of those commitees.... our idea is for example use shortcodes for this part on front page, like [service_body_logo="122"] ....
@radius314 .... how works those querystrings? give me a sample....

Tks for your service

**Comment by otrok7** [comment]
Hi, I think Danny's suggestion is the best (as usual), at least for now.  By default the query string of the URL is something like ?current-meeting-list=1.  If you want Bread to ignore the service entity you gave in your configuration, and use another the query string would be something like ?current-meeting-list=1&custom_query=%26services[]=4. where "4" is the ID of the service body you want Bread to process.  This won't change the logo, just the meetings, name of service area, stuff like that.  The logo for the service body isn't in the BMLT, although that is a feature request for the Core, that I think is a pretty good idea and pretty doable.  But if you just use a generic logo (for now) this will get you up and running right away.

**Comment by abna-brasil** [comment]
Ok, understood! But, as a sugestion, think about create for next versions the possibility of templates to help who has so many service bodies as us. This feature could be very usefull to change many confs more fastly

**Comment by radius314** [comment]
You can change a couple of other things too.   Check out this blog article: https://bmlt.app/reusable-templates-with-bread-1-6-x/

**Comment by radius314** [comment]
There is a demo of this running here: https://usa-tally.bmlt.app/map.html.

Click any state and then click any state and then the meeting schedule button.  This all uses the same bread template.

**Comment by abna-brasil** [comment]
@radius314 ... this is awsome... how to make it here?

**Comment by abna-brasil** [comment]
we already have a clickable map...
https://www.csa-saopaulo.org/newmap/

**Comment by radius314** [comment]
Here is the code for the USA map.

https://github.com/bmlt-enabled/usa-tally

**Comment by abna-brasil** [comment]
We are using WP.... my question is: what is the shortcode to show a specific state?

**Comment by radius314** [comment]
I'm not sure if this is a bread question or a crouton question now.

**Comment by abna-brasil** [comment]
you are right... it is a crouton question...

**Comment by radius314** [comment]
Happy to respond on a crouton ticket.  We should keep this to bread here.
