### ISSUE TITLE
pdf meeting list for all meetings.  need correct query string configuration

### ISSUE THREAD

**Issue by kramer123** [bmlt-enabled/bread#155]
On the Orlando GOASCNA website we have links for "in -person" & "virtual meetings" 
on our (bread) Meeting List configuration area,  , http://orlandona.org/?current-meeting-list=1  custom query for in-person  is &services=128&formats=-340
http://orlandona.org/?current-meeting-list=2 custom query for virtual meetings is &services=128&formats=341
**what would be the correct custom query configuration to generate both in person and virtual on** 
(all current meetings)  http://orlandona.org/?current-meeting-list=4    ?
any help appreciated

**Comment by tempsaint** [comment]
Hi @kramer123 , 
You can use the Additional List section on the meetings tab (in bread config) to put the virtual meetings on the same list but separate from the in-person meetings. That way you can format them differently.  You can look at the meeting lists we just setup for Connecticut ([http://ctna.org/find-a-meeting](http://ctna.org/find-a-meeting)) and you can check out a walk-through video here: [https://www.youtube.com/watch?v=zlAx9IZe2kE](https://www.youtube.com/watch?v=zlAx9IZe2kE)

**Comment by kramer123** [comment]
I'll have to watch that youtube video again later and figure it out, thanks
