### ISSUE TITLE
error when activating on new wordpress site

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/bread#159]
Hi, we have a new wordpress site in our area and I just installed Bread so we could start creating the meeting lists on the area site instead of the region's meetinglist multi site and get this error... Any idease what might be the problem?

Plugin could not be activated because it triggered a fatal error.
 Fatal error: Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/na-wt.org/wordpress/wp-content/plugins/bread/lang/translate_fa.php:6 Stack trace: #0 /var/www/na-wt.org/wordpress/wp-content/plugins/bread/bmlt-meeting-list.php(315): include() #1 /var/www/na-wt.org/wordpress/wp-content/plugins/bread/bmlt-meeting-list.php(129): Bread->load_translations() #2 /var/www/na-wt.org/wordpress/wp-content/plugins/bread/bmlt-meeting-list.php(2469): Bread->__construct() #3 /var/www/na-wt.org/wordpress/wp-admin/includes/plugin.php(2299): include('/var/www/na-wt....') #4 /var/www/na-wt.org/wordpress/wp-admin/plugins.php(191): plugin_sandbox_scrape('bread/bmlt-meet...') #5 {main} thrown in /var/www/na-wt.org/wordpress/wp-content/plugins/bread/lang/translate_fa.php on line 6

**Comment by otrok7** [comment]
Hi Lucy,  
This function is part of a PHP extension module, mbstring, that needs to be enabled in your PHP configuration, although I think it is usually in the default config of most service providers.  This is usually a matter of uncommenting a line in your php.ini file.  More information is here: https://www.php.net/manual/en/book.mbstring.php

Hope that helps.  Maybe someone with more experience managing websites on different providers can be more helpful.
Hugs.
Ron
