### ISSUE TITLE
Line Height on Custom Content - only adjusts full lines

### ISSUE THREAD

**Issue by dragonmacpc** [bmlt-enabled/bread#161]
Although you can tick the Line Height up to 1.1, 1.2, etc. it will not save and reverts to 1. You can only adjust it 2.0, 3.0 etc. Would like to be able to save at 1.2 or .3.  

WP version 5.6.2
WP Bread Plugin Version 2.5.8
PHP (7.1.33)

**Comment by otrok7** [comment]
Fixed in next release

**Comment by otrok7** [comment]
fixed in 2.6.0
