### ISSUE TITLE
auto_tz_adjust option for Bread like Crouton

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bread#163]
We have an Outreach use case where isolated members have no access to internet but can dial into virtual meetings by phone.  We want to be able to send them printed lists of the Virtual NA meeting data printed from the same time zone as them so they have a wide variety of meeting options to attend.  We've also explained how to read and use the list on the back [page](https://www.na.org.au/multi/na-at-home/?current-meeting-list=1).

Currently Bread does not adjust for timezone like Crouton and the list isn't accurate if you're not in the same time zone as the meetings.
Options we've thought about are:
1. Simply printing the web pages out
2. Copy and paste the text in the table to a new document
3. Putting in a feature request to Crouton to allow printing of just the visible list

**Comment by otrok7** [comment]
Well, good psychology, to say "Crouton can do it".  I can't let that go ;-)
What I'm thinking is adding this to the query_string, so you'd get it like http://bread.bmlt.org/?current-meeting-list=1&tz_adjust=+60
Is that what you are looking for?

**Comment by otrok7** [comment]
After talking to Jonathan, I have a better idea of what is required here.  Each meeting has a timezone, and that needs to be used to generate the meeting list for the target timezone.  Target timezone will be specified like  http://bread.bmlt.org/?current-meeting-list=1&time_zone=Europe/Moskow

Please try https://github.com/bmlt-enabled/bread/releases/download/2.6.0-beta1/bread.zip

**Comment by dragonmacpc** [comment]
Just asking this, it will not break the current linking, correct? ie any links "w/?current-meeting-list=3" no tz variable 

I ask because I have several links distributed. with new changes to printable lists changing fairly regular, as things open/close, Our best solution for printing meeting lists for groups is have them print a few before each meeting themselves.

**Comment by otrok7** [comment]
No, the start time of the meeting is only adjusted if (1) there is a timezone associated with the meeting, and (2) there is a target time zone specified in the query.  Otherwise your meeting lists are unaffected.

**Comment by otrok7** [comment]
Beta for testing: https://github.com/bmlt-enabled/bread/releases/download/2.6.0-beta2/bread.zip

**Comment by brustar64** [comment]
Hi I tested this but I couldn't see any difference from the current implementation.
Printed list still outputs the same time as they are entered into the database rather than the timezone in which they are viewed/printed in.  EG - https://www.na.org.au/multi/online-meetings/   VS   https://brucegardner.net/WP1/?current-meeting-list=1  (Beta Testing site)

**Comment by otrok7** [comment]
Hi Bruce!  I understood your use case, that you were *sending* the meeting lists to members that were not online themselves.  So I didn't use the timezone of the person printing the list, rather I require you to specify it in the URL, as I described in my comment 2 days ago.  Is that OK?

BTW, I notice that you have hrsHR in your meetinglist, is that intentional?  Or do you want [hrs]HR?

**Comment by brustar64** [comment]
Thanks. Maybe I misunderstood. What syntax should I use I enter a timezone such as UTC +10 (Brisbane) VS UTC +8 (Perth)?


Bruce

________________________________

**Comment by otrok7** [comment]
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

I could also provide an alternative way to specify the timezone.  For instance, something like "&utc=+10"

**Comment by brustar64** [comment]
I looked up the list of TZ timezones and it appears that I should use +10:00 right?
It still doesn't have any effect - https://brucegardner.net/WP1/?current-meeting-list=1&tz_adjust=+10:00

**Comment by otrok7** [comment]
https://brucegardner.net/WP1/?current-meeting-list=1&time_zone=Australia/Brisbane

**Comment by brustar64** [comment]
Perfect! Thanks very much!
