### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/bread#165]
When I attempt to generate a meeting list for nortcerncountiesna.org I get a long list of php errors.

I've compared the setting for the list with another site that is fully functioning and they are similar with the only difference being font sizes.

This is the output from the site:

Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php on line 742

Warning: file_get_contents(/tmp//ttfontdata/dejavusanscondensed.mtx.json): failed to open stream: Permission denied in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 68

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3869

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3875

Notice: Undefined index: fontmetrics in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3883

Notice: Undefined index: ASM in /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php on line 932

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Warning: file_get_contents(/tmp//ttfontdata/dejavusanscondensedB.mtx.json): failed to open stream: Permission denied in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 68

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3869

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3875

Notice: Undefined index: fontmetrics in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3883

Warning: file_get_contents(/tmp//ttfontdata/dejavusansmono.mtx.json): failed to open stream: Permission denied in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 68

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3869

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3875

Notice: Undefined index: fontmetrics in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3883

Warning: file_get_contents(/tmp//ttfontdata/dejavusansmonoB.mtx.json): failed to open stream: Permission denied in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 68

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3869

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3875

Notice: Undefined index: fontmetrics in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3883

Warning: file_get_contents(/tmp//ttfontdata/dejavusanscondensedI.mtx.json): failed to open stream: Permission denied in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 68

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3869

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3875

Notice: Undefined index: fontmetrics in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3883

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined offset: 17 in /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php on line 1768

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php on line 1768

Notice: Undefined offset: 17 in /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php on line 1769

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php on line 1769

Notice: Undefined index: bgcolorarray in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 18444

Notice: Undefined index: MyFooter in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Tag/SetHtmlPageFooter.php on line 50

Notice: Undefined index: MyFooter in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Tag/SetHtmlPageFooter.php on line 61

Notice: Undefined offset: 0 in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Writer/BaseWriter.php on line 205

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Writer/BaseWriter.php on line 205

Notice: Undefined offset: 0 in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Writer/BaseWriter.php on line 205

Notice: Trying to access array offset on value of type null in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Writer/BaseWriter.php on line 205

Fatal error: Uncaught Mpdf\MpdfException: Data has already been sent to output (/home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php at line 742), unable to output PDF file in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php:9512 Stack trace: #0 /home/northern/public_html/wp-content/plugins/bread/bmlt-meeting-list.php(1131): Mpdf\Mpdf->Output('meetinglist_1_4...', 'I') #1 /home/northern/public_html/wp-includes/class-wp-hook.php(292): Bread->bmlt_meeting_list('') #2 /home/northern/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #3 /home/northern/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #4 /home/northern/public_html/wp-settings.php(423): do_action('plugins_loaded') #5 /home/northern/public_html/wp-config.php(92): require_once('/home/northern/...') #6 /home/northern/public_html/wp-load.php(37): require_once('/home/northern/...') #7 /home/northern/public_html/wp-blog-header.php(13): require_once('/home/nort in /home/northern/public_html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 9512

Please help I've tried deleting bread and reinstalling the latest version and get the same results.

**Comment by otrok7** [comment]
Hi Eddie, 

it seems you have your debug level set very high, and you are outputting the debug log to the browser.   This is the second error like this, so I will consider suppressing error messages in the next release of Bread.  In the meantime. please set `define( 'WP_DEBUG', false );` in your wp-config.php.

If that doesn't help, then you have have debugging set in your php.ini, and you will need to change it there or add `ini_set('display_errors','Off');` to your wp-config.php, too.

Let me know if this helps.

**Comment by EddieW1** [comment]
Thanks for the help here.

I’ve set the wp_debug, false in the wp config file and now the file is generating the directory.

Might be time to consider making bread PHP 8 ready by replacing deprecated calls and functions with current language.

Also they have the front page created as a word doc that they imported which hard codes the font settings of bread.

I’ll need to work with their admin to try to fix that so the directory can be printed on 1 2 sided tri-fold.

Thanks again for the support and the quick response.

ILS
Eddie
