### ISSUE TITLE
Bread meeting list generation hangs

### ISSUE THREAD

**Issue by otwna** [bmlt-enabled/bread#166]
Bread hangs and does not load meeting list. Single service body.  Latest version of Bread. 

https://www.wyo-braskana.org/?current-meeting-list=1

Protocol: https://
PHP Version: 7.3.2
Server Version: Apache/2
Temporary Directory: /tmp/

[wyo-braska-area-of-narcotics-anonymous-default-setting04-17-2021.zip](https://github.com/bmlt-enabled/bread/files/6330162/wyo-braska-area-of-narcotics-anonymous-default-setting04-17-2021.zip)

**Comment by otrok7** [comment]
There's nothing wrong with your bread configuration, I can generate a PDF with no problem.  There must be something in your system that is causing the problem.  As a first try, lets hope that we see something when debugging is turned on.  You mentioned that you had WP_DEBUG defined to false.  Please replace this with 

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true);
define( 'WP_DEBUG_DISPLAY', false);
```
and then send me whatever comes out in wp-contents/debug.log when you try to generate a PDF.  If there's no output, then write that here, and we will have to consider some stuff that takes a little extra effort.

**Comment by otwna** [comment]
Thanks, here's the log. Not sure why, but it does work now that logging is turned on. Maybe a coincidence. There are errors in the log.  
[debug-wyo.txt](https://github.com/bmlt-enabled/bread/files/6354280/debug-wyo.txt)

**Comment by otrok7** [comment]
Thanks.  This looks like more of the same problems other users have been having lately, with temp files not being properly cleaned up.  Please deploy the following beta, and see if it helps:

https://github.com/bmlt-enabled/bread/releases/tag/2.6.1-beta2

**Comment by otwna** [comment]
I installed the beta and disabled logging and it works. Thanks!
