### ISSUE TITLE
It need some French translated feature

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/bread#169]
I cannot add French format, neither bilingual format (French and English)
![Screenshot 2021-04-25 153541](https://user-images.githubusercontent.com/3509271/116007084-05957080-a5dc-11eb-9c5d-6e5db470fc71.png)

**Comment by otrok7** [comment]
It's the labelling of the dropdown menu that is incorrect.  All the so-called "English" options will actually use whichever language you selected on the "Meetings" tab, as the "Weekday Language".  I will change the labelling in the next release, but until then, you can still create French lists.

**Comment by Klodd65** [comment]
![Capture d’écran 2021-04-25 174844](https://user-images.githubusercontent.com/3509271/116010698-95441a80-a5ee-11eb-8cc0-e07a0247c5bd.png) #
