### ISSUE TITLE
Sort by municipality

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/bread#171]
We are using a custom query to select more than one local Area Service body and leave out virtual meetings. We are trying to sort by municipality, but when we include &sort_keys=location_municipality in the query the sort still comes out by time and then group name. We are listing municipality before group name on our formatted output and want to sort by time then municipality. Can this be done?

**Comment by otrok7** [comment]
Sorting is not done in the query, but using the "group by" drop-down in the "Meetings" tab.  This gives a sort by city, and, within each city, by day/time.
