### ISSUE TITLE
Virtual meeting info not showing in Bread

### ISSUE THREAD

**Issue by CORegionalweb** [bmlt-enabled/bread#178]
Info in the virtual meeting info field is not showing up in printed meeting lists.  https://nacolorado.org/?current-meeting-list=1

**Comment by californiasteve** [comment]
Have you checked this box on the BMLT Server tab?![20211124_191152.jpg](https://user-images.githubusercontent.com/31661648/143334617-d9baccc0-d5f6-460d-b74f-ccbaffc574b3.jpg)

**Comment by CORegionalweb** [comment]
Hi thanks for the reply, I did not have that checked. I enabled it and refreshed and no change. I looked around and found that i had not added the virtual_meeting_info field to the template. Looking good now, thanks.
