### ISSUE TITLE
hybrid meetings not displaying on additional list again

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bread#179]
This issue was previously fixed in Issue #151 but the problem is back. We have our Additional List set to Virtual Meetings (near the top of the dropdown list - not the singular "virtual meeting" entry down towards the bottom of the dropdown list) yet all Hybrid meetings are being excluded from the additional list. 

I've tried switching to a different type and then switching back but that doesn't resolve the issue.  

I'm attaching an affected meeting list (you'll see there's HY meetings on Wednesday and Friday) as well as the json (zippped because I couldn't attach a json file) for the same list. 

[meetinglist_11_122220215050549.pdf](https://github.com/bmlt-enabled/bread/files/7764140/meetinglist_11_122220215050549.pdf)
[connecticut-region-of-narcotics-anonymous-waterbury-area12-22-2021.json.zip](https://github.com/bmlt-enabled/bread/files/7764144/connecticut-region-of-narcotics-anonymous-waterbury-area12-22-2021.json.zip)

**Comment by tempsaint** [comment]
I just tested bread version 2.6.0 and everything worked properly with that version.

**Comment by tempsaint** [comment]
Hi Ron, I'm sure you're busy but I was hoping maybe you'd be able to get back to this some day?

**Comment by otrok7** [comment]
Should be fixed in 2.7.0.   Please confirm.

**Comment by tempsaint** [comment]
This is fixed in 2.7.0. Thank you Ron.
