### ISSUE TITLE
problems with format legends in languages other than English

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/bread#183]
There is an existing shortcode for format legends in Spanish `[format_codes_used_basic_es]`, and a PR to add this for French (#182).  Several issues:

1. This seems like the wrong way to handle this.  Better would be adding an optional language parameter to `[format_codes_used_basic]` that defaults to English.
2. The php for these shortcodes include a translation into Spanish or French, embedded in the program itself.   Bad.  Instead the shortcode `[format_codes_used_basic]` should get the appropriate translation from the corresponding file in the lang/ subdirectory, based on the language parameter.
3. There is another shortcode `[format_codes_used_detailed_es]`but it's broken.  This should be fixed, and similarly replaced by a shortcode `[format_codes_used_detailed]` with an optional language parameter.
4. The shortcodes `[format_codes_all_basic]` and `[format_codes_all_detailed]` are only available for English.  They too should have the same optional parameter so that they are available in all languages.

**Comment by otrok7** [comment]
Hi Alan,  the format_codes_used short code does not default to English, but to whatever language was selected as the "Weekday Language".  I've never gotten a feature request for formats codes in a different language that the weekday language.   

You are correct that having specialized shortcodes for some languages is not very nice if you are interested in an unspupported language.  We should treat all languages similarly.  However, these shortcodes are more or less deprecated, are are left there for backwards compatibility. 

So: Is this a bug report that the shortcode is in a language other than the weekday language?  Or is this a feature request for the ability to produce a format list in a language other than the weekday language.

Thanks

**Comment by alanb2718** [comment]
Ah ok.  This is a bug report then.  Even if the weekday language is French, the format legends are in English.  I'll email you the configuration that they sent me.

**Comment by otrok7** [comment]
fixed in next release

**Comment by alanb2718** [comment]
Tested - it's working now!
