### ISSUE TITLE
mPDF Curl User Agent being rejected by SiteGround

### ISSUE THREAD

**Issue by spiritualtheory** [bmlt-enabled/bread#190]
Recently discovered that all 12 or so Bread Templates on 6 subdomains were failing to load their images when generating a meeting list, but the images showed up in the template editor. However, Bread could still generate the image hosted externally on bmlt.app

Was pointed in the direction of the curl user agent setting by Alan as that was a recent issue with the rootserver and SiteGround

Went into plugins/bread/mpdf/vendor/mpdf/mpdf/src/confic/ConfigVariables and changed

'curlUserAgent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:13.0) Gecko/20100101 Firefox/13.0.1',

to

'curlUserAgent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0',

and then the meeting lists generated correctly - with images and all.

Can this setting be updated in the next release of Bread?

**Comment by klgrimley** [comment]
I was having the same issue. Updating as @spiritualtheory suggested worked for me. Looking at the mPDF repo there was a [commit last week on the development branch](https://github.com/mpdf/mpdf/commit/c7c2a89bbb5f6117e0a5b778c4c4aae936414307) that updated this also. The update bumped the Firefox version from 13 to 108. Tested on my install and works as expected. Has not been released yet but hopefully it'll be in the next one.

**Comment by otrok7** [comment]
Please send me the JSON export of the file so that I can try to reproduce the problem.

**Comment by otrok7** [comment]
It is generally possible to set mPDF configuration from Bread, but I need to test first.  This would be much simpler that trying to change code inside of mPDF, just because of the way the build works.  If you send me the JSON, I can make the test and make the change in pretty short order.

**Comment by spiritualtheory** [comment]
[Finger Lakes Area JSON.zip](https://github.com/bmlt-enabled/bread/files/10476741/Finger.Lakes.Area.JSON.zip)

It currently works because I made the changes in the mPDF code listed above

This also currently is only an issue on websites hosted by SiteGround, so reproduction of the issue will require having security settings for the curl UA of your host set high enough to imitate SiteGround.

**Comment by otrok7** [comment]
Rather than modifying MPDF, you can change its configuration by using an extension to Bread.  In your functions.php add:
`add_filter( 'Bread_Mpdf_Init_Options', 'bread_ext_mpdf_init', 10, 2);
function bread_ext_mpdf_init($mpdf_config, $bread_config) {
    $mpdf_config['curlUserAgent'] = 'whatever you want';
    return $mpdf_config;
}`

**Comment by spiritualtheory** [comment]
Can this be fixed / revised in Bread so when the next Bread update comes around we don't need to manually update all installations of Bread that are hosted on SiteGround? Perhaps put this in Bread so that the default setting is something much newer?

**Comment by otrok7** [comment]
The idea is that the modification is in your functions.php, so that you don't have to change it when the plugin updates.
This extension point was added to exactly to handle use cases like this.  I'd rather wait for MPDF to change this, and not modify Bread as changing the User Agent might cause problems on other sites.

**Comment by jbraswell** [comment]
Seeing more and more instances of this in the wild. We really need a fix for this besides asking users to make source code modifications that will be overwritten on upgrade. We should set a default user agent the same as the one in the mpdf commit that Kevin linked.

**Comment by otrok7** [comment]
I'd rather not overwrite mPDF more than necessary.  The solution I have does not require modifications with each new update, it is a mod in the users themes functions.php, which will survive updates to Bread.  The extension point was added especially to handle such use cases.

**Comment by jbraswell** [comment]
https://github.com/mpdf/mpdf/commit/c7c2a89bbb5f6117e0a5b778c4c4aae936414307

Did you see this? This was merged to the mpdf main branch, but is unlikely to be released in the near future. I really think we should use this same user agent and cut a release. I bet a lot of meeting lists are broken where no one has noticed or knows how to reach out for help. SiteGround is a very popular web host for area websites. 

I understand what you are saying from a code purity standpoint, but practically speaking, this is an extremely simple change and it is better to just update the user agent than die on the code purity hill. We can always revert the change later.

**Comment by klgrimley** [comment]
Just my two cents.... In addition to what @jbraswell just said, asking a "normal" webservant to modify their theme functions.php file isn't a great idea. Most aren't developers, and changing code is terrifying. Maybe a slight exaggeration there but you get the idea. Additionally it wouldn't surprise me if many of them aren't using child themes ( again refer to my they're not developers comment ) so it would just get overwritten during the next theme update. 

It would be great if that new release with the updated useragent got pushed soon but they don't seem to release much. Until it happens and can be brought into bread I agree with Jonathan that it should be changed in the bread plugin

**Comment by otrok7** [comment]
OK, I guess the group conscience has spoken.  It will be in the next release, which I will make as soon as I figure out when and why Bread doesn't clean up after itself.

**Comment by spiritualtheory** [comment]
This is still an issue that persists in the most recent version of Bread

Still have to manually go into the mPDF config to set the user agent there to 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0'

**Comment by otrok7** [comment]
When I test locally using the FingerLakes JSON above, I see the NA Logo on page 3.  Is there another graphic I should be seeing?  

As I wrote previously, it is far better to update your functions.php than to modify the plugin code or the libraries used by the plugin.  But whether or not that is your preferred work around, will you please try it and let me know if it solves the problem, too.  Because that essentially what I did to try and fix the problem, and I would like to know if I should be taking another approach.

**Comment by spiritualtheory** [comment]
https://nny-na.org/?current-meeting-list=2 shows what Finger Lakes is supposed to look like. Has a QR code plus a picture of our symbol (pyramid version)

The previous fix in functions.php didn't seem to work, so I had gone back to modifying the mPDF config - which the quickest and easiest way to keep updating the Bread plugin has been to modify the mPDF config - which I end up defaulting to anyways because I help take care of multiple sites.

**Comment by otrok7** [comment]
When I look at the json, the href to the image for the QRCode seems to point to nowhere.  Do I have your latest JSON?

**Comment by otrok7** [comment]
Unless each site is using a different theme, you only need one functions.php

**Comment by spiritualtheory** [comment]
Different sites, different themes, realistically should not be having to edit functions.php to make the plugin work - I can do that, but many are not going to grasp what's going on or how to go about fixing it.

[Finger Lakes area json template.zip](https://github.com/bmlt-enabled/bread/files/11073469/Finger.Lakes.area.json.template.zip)

**Comment by jbraswell** [comment]
There's an area in Carolina Region having this same issue.

**Comment by otrok7** [comment]
Jesus, gimme a second, willya

**Comment by otrok7** [comment]
left out a place where MPdf was getting initialized.  Tested locally and it works.  New release on its way.

**Comment by otrok7** [comment]
2.7.8 should fix this.  Please test it.  But it's late here, so if it still is broken, then send a note and I will get to it tomorrow.

**Comment by otrok7** [comment]
Unless I hear otherwise, I will assume your test is OK and close this issue

**Comment by spiritualtheory** [comment]
I will test this later this evening - have not had time since the update

**Comment by spiritualtheory** [comment]
Appears to work, thank you
