### ISSUE TITLE
Fatal Error when creating PDF file, not sure what to do.

### ISSUE THREAD

**Issue by southatlanticna** [bmlt-enabled/bread#192]
Fatal error: Uncaught Mpdf\MpdfException: Temporary files directory "/mpdf" is not writable in C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-content\plugins\bread\mpdf\vendor\mpdf\mpdf\src\Cache.php:21 Stack trace: #0 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-content\plugins\bread\mpdf\vendor\mpdf\mpdf\src\ServiceFactory.php(67): Mpdf\Cache->__construct('/mpdf', 3600) #1 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-content\plugins\bread\mpdf\vendor\mpdf\mpdf\src\Mpdf.php(1083): Mpdf\ServiceFactory->getServices(Object(Mpdf\Mpdf), Object(Psr\Log\NullLogger), Array, Object(Mpdf\Language\LanguageToFont), Object(Mpdf\Language\ScriptToLanguage), NULL, NULL, NULL, NULL) #2 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-content\plugins\bread\bmlt-meeting-list.php(875): Mpdf\Mpdf->__construct(Array) #3 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-includes\class-wp-hook.php(308): Bread->bmlt_meeting_list('') #4 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #5 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #6 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-settings.php(480): do_action('plugins_loaded') #7 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-config.php(93): require_once('C:\\Users\\Ben Be...') #8 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-load.php(50): require_once('C:\\Users\\Ben Be...') #9 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-blog-header.php(13): require_once('C:\\Users\\Ben Be...') #10 C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\index.php(17): require('C:\\Users\\Ben Be...') #11 {main} thrown in C:\Users\Ben Beller\Local Sites\meetingssouthatlanticnalocal\app\public\wp-content\plugins\bread\mpdf\vendor\mpdf\mpdf\src\Cache.php on line 21

**Comment by southatlanticna** [comment]
This is on a local version of a brand new site with no plugins. Got a similar error when trying to use the live site.

**Comment by southatlanticna** [comment]
Linux

**Comment by southatlanticna** [comment]
The error is a different on the live server 

Fatal error: Uncaught Error: Call to undefined function Mpdf\Color\ctype_xdigit() in /hermes/bosnacweb06/bosnacweb06ao/b2116/ipg.southatlanticna44134/southa/wordpress/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Color/ColorConverter.php:361 Stack trace: #0 /hermes/bosnacweb06/bosnacweb06ao/b2116/ipg.southatlanticna44134/southa/wordpress/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Color/ColorConverter.php(221): Mpdf\Color\ColorConverter->safeHexDec('ff') #1 /hermes/bosnacweb06/bosnacweb06ao/b2116/ipg.southatlanticna44134/southa/wordpress/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Color/ColorConverter.php(194): Mpdf\Color\ColorConverter->processHashColor('#ffffff00') #2 /hermes/bosnacweb06/bosnacweb06ao/b2116/ipg.southatlanticna44134/southa/wordpress/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Color/ColorConverter.php(52): Mpdf\Color\ColorConverter->convertPlain('#ffffff00', Array) #3 /hermes/bosnacweb06/bosnacweb06ao/b2116/ipg.southatlanticna44134/southa/wordpress/wp-content/plugins/bread/mpdf/v in /hermes/bosnacweb06/bosnacweb06ao/b2116/ipg.southatlanticna44134/southa/wordpress/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Color/ColorConverter.php on line 361

**Comment by pjaudiomv** [comment]
can you provide the following

WordPress Version:
PHP Version:
Bread Version:

**Comment by southatlanticna** [comment]
WordPres 6.1.1
MySQL 5.6.32
PHP 7.4.10
Bread Version: 2.7.3

**Comment by pjaudiomv** [comment]
if you have access to cpanel or similar you may try going to PHP Extensions and seeing if `ctype` is checked and enabled

**Comment by pjaudiomv** [comment]
could save you a support ticket with hosting

**Comment by pjaudiomv** [comment]
![Screen Shot 2023-02-13 at 8 18 24 PM](https://user-images.githubusercontent.com/34245618/218613294-e6e6fd8d-a85b-48d3-b73d-7ef21c476e52.png)

**Comment by southatlanticna** [comment]
Awesome, that worked thank you!

**Comment by southatlanticna** [comment]
On my webhost I had to add "extension=ctype.so" at the end of the php.ini file.

**Comment by pjaudiomv** [comment]
awesome, good to hear
