### ISSUE TITLE
Custom Query

### ISSUE THREAD

**Issue by southatlanticna** [bmlt-enabled/bread#193]
How do I create a custom query to create meeting lists by county? Can I put something in the query to help reduce or eliminate duplicate meetings.

**Comment by californiasteve** [comment]
You can use this &meeting_key=location_sub_province&meeting_key_value=CountyYouWant
As far as duplicates I would remove them from the BMLT Server

**Comment by southatlanticna** [comment]
That worked thank you!

**Comment by southatlanticna** [comment]
Where can I find information on how to create a custom query? The one for
the county is great now I need one to exclude online meetings and area
service meetings.
