### ISSUE TITLE
Time formats in two-column layouts

### ISSUE THREAD

**Issue by TheRichWoods** [bmlt-enabled/bread#195]
![Screenshot 2023-03-18 095334](https://user-images.githubusercontent.com/7906450/226110327-b2986787-a9f1-4839-a614-809ba9fc953b.jpg)
Is it possible to fix the text wrapping on the times when using the two-column layout?

**Comment by otrok7** [comment]
There is an option to add whitespace into the time format.  This will allow the system to break up the string in a more reasonable manner.  Alternatively, you can change the width of the column, or the font size.  In your case, I would recommend using the 8:00PM-9:00PM format with whitespace added.  This will make all the times take up the approximately same amount of space, so everything will appear more regular, and then play a bit with the column's width.  Is that an option for you?

**Comment by otrok7** [comment]
I'm assuming the suggested solution was OK, and am closing the issue.
