### ISSUE TITLE
Bread not displaying meetings without formats

### ISSUE THREAD

**Issue by spiritualtheory** [bmlt-enabled/bread#196]
Meetings that do not have format codes are not being displayed on Bread meeting lists

This holds true across multiple sites / installations / templates

Add a format to a meeting and it appears again. Remove it and it disappears. Doesn't matter what format.

This is new as of February as there were printed meeting lists at that time that still included meetings with no formats. Now those same templates lack meetings without formats.

**Comment by spiritualtheory** [comment]
Reverting to 2.7.3 fixes the issue

**Comment by otrok7** [comment]
@spiritualtheory - thanks for the very complete bug report, including the JSONs on Slack, comparing with older version.... that made it easy to identify the bug.  At least I hope.  Please verify and close the issue if it is fixed.

**Comment by spiritualtheory** [comment]
The issue is fixed with the most recent revision, but the issue with SiteGround losing external images is back - I have to manually go in and edit mPDF's config to replace the cURL agent with 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0'
