### ISSUE TITLE
BMLT Connection issue

### ISSUE THREAD

**Issue by tpmerrill** [bmlt-enabled/bread#204]
I'm using WordPress for my site and connecting it to BMLT.  Recently we changed web hosting to Hostinger, and since that time I cannot connect to BMLT to edit settings.  I looked at the Java Console to see if there were issues, and I got the attached two responses.  Does anyone have any ideas what I can do?
![Annotation 2023-10-04 123340](https://github.com/bmlt-enabled/bread/assets/146986308/eae70937-5e49-47e0-8058-dd1da5b73d5e)
![Annotation 2023-10-04 123341](https://github.com/bmlt-enabled/bread/assets/146986308/4ed7d7a5-35a2-4f12-a2c6-1d27b9c25dda)

**Comment by otrok7** [comment]
Hi, @tpmerrill , please turn on Wordpress debugging... I need more information on this 500 error.  Also, can you use Bread to print meeting lists, or does that crash too?  One last thing, which root server are you trying to connect to.

**Comment by tpmerrill** [comment]
Yes, that's how we do printed meeting lists, and I can't even get to that section since it gets stuck at "Connecting to BMLT".  The root server is https://natennessee.org/main_server.  I inherited this site, so I'm not up to speed on some things.  How do I turn on Wordpress debugging?  I did click through the error message and got the attached screen.  Does this help?
![Annotation 2023-10-04 144424](https://github.com/bmlt-enabled/bread/assets/146986308/717abb67-c6dc-4870-a818-e581e34a2fcc)

**Comment by californiasteve** [comment]
I just checked to websites that I use bread on that connect to the Kentucky server and they are working.
https://chicagona.org/?current-meeting-list=1
http://sfna.org/?current-meeting-list=1

**Comment by californiasteve** [comment]
I was just in Nashville last week.

**Comment by californiasteve** [comment]
I'm thinking it's a memory issue since crouton is accessing the BMLT server just fine.

**Comment by tpmerrill** [comment]
Thanks for the response.  Is that something I correct in Wordpress, or the web host Hostinger?

**Comment by californiasteve** [comment]
You would have to add a line of code to the file wp-config.php
Add this to the top, before the line that says, “Happy Blogging”:
define('WP_MEMORY_LIMIT', '512M');

**Comment by californiasteve** [comment]
Using the Cpanel and file editor. If you need help I can jump on zoom with you and walk you through it.

**Comment by otrok7** [comment]
Turning on debugging is also done by editing wp-config.php.  You would need to add lines like: `define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );`.  That will print whatever is causing the HTTP 500 to the browser.  You want to make a copy of what it says and then remove the lines, because you don't want messages like that going to your users.  But try what Steve is suggesting first.  It seems like he's seen problems like this before.

**Comment by otrok7** [comment]
@tpmerrill , is this still an issue?
