### ISSUE TITLE
Issue with upgrading bread to 2.8.1

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bread#215]
my site was on 2.7.1 and I just upgraded to 2.8.1 and now my configuration is gone and none of my settings are there. It shows `array` in my configuration name and server settings are gone

<img width="792" alt="Screenshot 2024-12-10 at 11 35 20 AM" src="https://github.com/user-attachments/assets/40c37afd-5360-4c2d-ba5b-91fb414a9046">
<img width="671" alt="Screenshot 2024-12-10 at 11 35 13 AM" src="https://github.com/user-attachments/assets/b9d68714-8500-48f7-a44f-7707cd0b546b">

**Comment by pjaudiomv** [comment]
I was able to import the configuration I had luckily saved first, at first I didnt think it worked but then i hit the save configuration name button and it worked. I'm wondering if i could of hit the save configuration name button without doing import and it would of just worked

**Comment by otrok7** [comment]
I haven't been able to reproduce this behavior.  Are you sure it was from 2.7.1?  Could it have been even older?

**Comment by otrok7** [comment]
Send me the JSON that you have...is it possible that you upgraded Bread, but never actually saved the file since Bread v1?  Up until this version, Bread never used to automatically update configurations, so unless you actively modified a setting, maybe the data was very old....
