### ISSUE TITLE
Export settings not working

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bread#216]
I noticed today when we try to export our settings, we instead get redirected to a page instead of getting the downloaded file.  

![Screenshot 2024-12-11 at 7 06 20 PM](https://github.com/user-attachments/assets/d0404db0-9e93-4760-99c9-f0e0f5b30ff2)

**Comment by otrok7** [comment]
Please send me your URL... I need to see if your browser isn't accepting the mime type, or if there's something wrong in the headers, or both.

**Comment by dgershman** [comment]
https://suburbanessexna.org/?current-meeting-list=1

**Comment by otrok7** [comment]
Thanks.  Got it.  Programmer Effect is the opposite of the General's Effect... On my WPs it works.

**Comment by otrok7** [comment]
sure wish someone would test this stuff while it's still in beta.

**Comment by dgershman** [comment]
😀
