### ISSUE TITLE
bmlt bread pulling other area's service meetings in Florida

### ISSUE THREAD

**Issue by kramer123** [bmlt-enabled/bread#217]
bmlt bread pulling other area's service meetings in Florida
on Orlandona.org   I think today 12/12/24 after latest update to 2.8.3   our paper generated list is showing all Florida service meetings.  
It was one paragraph now it two extra pages. 
I tried rolling update back to 2.8.2 and 2.8.1,  cleared cache on wp and history on browser.  
Our pulled meetings displaying on website are fine, just on the generated pdf list?

**Comment by kramer123** [comment]
OK so rolling back to 2.7.9 it works fine ,  2.8.0 or higher whacks out the "service_meetings" displayed?

**Comment by otrok7** [comment]
Please export your settings and send me the JSON.  Either attach them here or DM me on the slack.

**Comment by kramer123** [comment]
Thanks for the response , here are the bread exported settings that work fine in 2.7.9  
[greater-orlando-area-of-narcotics-anonymous-in-person-meetings12-13-2024.json](https://github.com/user-attachments/files/18127603/greater-orlando-area-of-narcotics-anonymous-in-person-meetings12-13-2024.json)

**Comment by kramer123** [comment]
seems ok now,  Thanks!
