### ISSUE TITLE
 layout in Tri-fold, portrait and Tabloid (11" X 17")

### ISSUE THREAD

**Issue by Lyn1992** [bmlt-enabled/bread#52]
How to fix white spacing on front and custom page.  Text unable to move to set margin at bottom of page.  Also, on the meeting page, shortcode is needed to be able to add spaces between headers and meetings.

**Comment by radius314** [comment]
Could you possibly include a screenshot showing the issue you want to resolve?

**Comment by Lyn1992** [comment]
Hi Danny,
I hope all is well with you. I'm doing good.
Attached is the meeting list I created with Bread. I'm trying to figure out
how to make space between the headers and bring text down to the margins. I
Also attached my previous meeting list which I created with adobe Indesign
to explain what I'm trying to do. I know the pages can't be flipped around
like it can with Indesign but I would like to correct the spacing.

Thank You for your outstanding work. You are greatly appreciated.
Lettie S. - Web Servant,GCANA

**Comment by radius314** [comment]
Thanks, not seeing an attachment.  You will to drag and drop them on to the ticket itself.

**Comment by radius314** [comment]
This may be related to #46

**Comment by radius314** [comment]
we have a patched version that's available for testing in the unstable branch

**Comment by radius314** [comment]
nm, this fix is for booklets not tri folds... still need a screenshot

**Comment by Lyn1992** [comment]
[image: image.png]
This I made with Bread but can't get text to bottom margins or space after
the headers

[image: image.png]
This is example of what I want to do, space between headings & texts go to
bottom margin
Thanks
Lettie

**Comment by radius314** [comment]
Still cannot see the attachments.  You will to go to github and drag and
drop the images in the comment box to attach them.

https://github.com/radius314/bread/issues/52

**Comment by Lyn1992** [comment]
<img width="1242" alt="screen shot 2018-11-08 at 12 57 50 am" src="https://user-images.githubusercontent.com/44745124/48242434-38fec900-e3a9-11e8-9124-a548a650238f.png">

<img width="1242" alt="screen shot 2018-11-08 at 12 57 50 am" src="https://user-images.githubusercontent.com/44745124/48242444-40be6d80-e3a9-11e8-88e6-52a9aedff883.png">

**Comment by Lyn1992** [comment]
<img width="1244" alt="screen shot 2018-11-08 at 1 05 44 am" src="https://user-images.githubusercontent.com/44745124/48242465-5a5fb500-e3a9-11e8-9d10-e56e65eaa9be.png">

**Comment by Lyn1992** [comment]
<img width="1242" alt="screen shot 2018-11-08 at 12 57 50 am" src="https://user-images.githubusercontent.com/44745124/48242490-782d1a00-e3a9-11e8-9efb-c8850f5d6e6c.png">

**Comment by Lyn1992** [comment]
This is what I'm try to achieve, no white spacing- next goes to margin at bottom of the page and spacing after the black headers

<img width="1244" alt="screen shot 2018-11-08 at 1 05 44 am" src="https://user-images.githubusercontent.com/44745124/48242544-a4e13180-e3a9-11e8-8b00-cffd92eff96e.png">

**Comment by Lyn1992** [comment]
<img width="1249" alt="screen shot 2018-11-08 at 12 59 19 am" src="https://user-images.githubusercontent.com/44745124/48242687-6435e800-e3aa-11e8-82e7-22335109197d.png">

**Comment by radius314** [comment]
Have you tried using `[page_break]`

**Comment by radius314** [comment]
Regarding the spacing issue after the day subheadings, are you are manually
setting this spacing?  If so, what logic are you applying?  We would need
to translate that logic into some kind of spacing algorithm.

**Comment by Lyn1992** [comment]
Hi Danny,
No, I haven't tried page break because I don't know html coding or were to insert this code.
 
I haven't figured out how to manually set this spacing.  My logic is that white space is a fundamental building block of a good design because it Improves legibility, higher comprehension or helps people understand what they are reading, just to name a few.

**Comment by radius314** [comment]
This is not HTML, it's a shortcode.  You insert the [page_break] after the place where you want to force a new page.

At this time it is not currently possible to insert an arbitrary amount of whitespace between section headers.  I'm not sure this feature would ever get built-in.   Ether because it would make the meeting schedule unmaintainable given that the moment that any of the content size blocks change, it would change the amount of whitespace required.  The basic fundamental of this plugin is that typically you do not need to intervene after changes happen, essentially automation.  

Given what you have proposed here, there would be no way to automate this, hence breaking a core principle of the plugin.

**Comment by Lyn1992** [comment]
Hi Danny,
Okay I understand. I deleted the default template by accident so I tried to
create my own.  How do I get the default template back.  See attached.

[image: image.png]
Thanks for all your help,
Lettie

**Comment by radius314** [comment]
under meeting list setup, click meeting list setup accordion.  you have 3 stock options.

**Comment by radius314** [comment]
The only obvious thing I can think to do is to be able to insert some kind of spacing before each subsection header.  This would be equidistant spacing.  Let me know if that sounds desirable.

**Comment by Lyn1992** [comment]
Hi Danny,
You wrote "under meeting list setup, click meeting list setup accordion. you have 3 stock options."
I do not see the accordion option 

![screen shot 2018-11-12 at 11 24 29 am](https://user-images.githubusercontent.com/44745124/48361391-65e40200-e66f-11e8-8fd9-38645b66d3fe.png)


You wrote "This would be equidistant spacing. Let me know if that sounds desirable"
This sound like it will only help with spacing between columns, I need the text in rows to go to the bottom of the page. I'll back up what's already there and try equidistant spacing, how do I to get it?

**Comment by radius314** [comment]
An accordion is a UI element.  It's when a section expands.  You can see there are three buttons here.

The equidistant spacing feature doesn't exist.  I was asking if it was desirable as a future feature before we spent time building something that wouldn't be used.
