### ISSUE TITLE
plugin doesn't obey any user roles/permissions

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bread#53]
This plugin doesn't obey any user roles/permissions. If I restrict a user to only be able to read and create posts, they can still change Bread settings. There is an edit plugin capability/permission so I would think that that setting would need to be enabled before a user can edit the settings.

**Comment by radius314** [comment]
This is an obvious thing that was just never baked in.  Believe it or not, you are the first person to realize this.

**Comment by radius314** [comment]
fix is in unstable branch, tested and it works... will be in bread 1.9.0
