### ISSUE TITLE
Exclude List

### ISSUE THREAD

**Issue by rdtripp** [bmlt-enabled/bread#59]
I'd like to be able to exclude an area from the printed regional meeting list.  We have several meetings in our geographic region that are registered with NAWS but don't want to be affiliated with a Region.  I'd like to be able to put them in an independent "area" so they will show up on meeting searches but can be excluded from our printed regional meeting list.

**Comment by radius314** [comment]
You can accomplish this with a custom query.  Use the semantic workshop to generate a query of service bodies you want to include/exclude.  The part that goes into the custom query will be the part after "GetSearchResults".

**Comment by rdtripp** [comment]
Thanks.  As usual you solved my problem.  Will do it that way.

**Comment by rdtripp** [comment]
What data format do I need to select?

**Comment by radius314** [comment]
It doesn't matter for what is eventually put in the field.  You will only be including the part after "GetSearchResults" into the text box.

**Comment by rdtripp** [comment]
OK.  You told me that to start with and it went right over my head.  Got it now.  Tried it and it does exactly what I need.  Thanks again.
