### ISSUE TITLE
Version comparison not working.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#60]
I noticed tonight that the version comparison isn't really working well.  It should probably hit github instead of Greater New York Region.

![zoom_meeting_id__755-478-9642](https://user-images.githubusercontent.com/1850811/51095653-50c94380-1784-11e9-8a53-54a3bdc241ec.png)

**Comment by pjaudiomv** [comment]
I noticed that too need to change source of truth

**Comment by pjaudiomv** [comment]
I think crouton is the same too

**Comment by radius314** [comment]
merged to unstable

**Comment by radius314** [comment]
released in 1.9.4
