### ISSUE TITLE
huge margin on booklet format

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#65]
after 1.9.4 the booklet format has a huge margin again, too much space before the page numbers

**Comment by pjaudiomv** [comment]
this is happening on tri-fold as well, had to roll back all my bread installs to 1.9.0. no way to adjust the margins to acceptable level. 

![Screen Shot 2019-04-11 at 6 37 06 PM](https://user-images.githubusercontent.com/34245618/55997611-1ee35280-5c89-11e9-99b7-0a8c80bb4411.png)
![Screen Shot 2019-04-11 at 6 36 52 PM](https://user-images.githubusercontent.com/34245618/55997612-1ee35280-5c89-11e9-8000-dc4089c0965a.png)

**Comment by radius314** [comment]
delivered in bread 1.9.8
