### ISSUE TITLE
Group Name Reading Short Code

### ISSUE THREAD

**Issue by DanielWright98** [bmlt-enabled/bread#69]
A group name "Sunday Simplicity" is generated as "Sunday SimpliTampa" by the Meeting List Generator.
It's been suggested that the plugin in reading the short code for [city] and inserting "Tampa" for "city" as the generates the meeting list.
The online meeting schedule looks right.
I learned about Bread the Florida Service Symposium. So I switched to Bread, but I get the same results.
Any help?

**Comment by radius314** [comment]
Can you share the PDF output and the config file?

**Comment by pjaudiomv** [comment]
[current_meeting_list_41220199095022.pdf](https://github.com/bmlt-enabled/bread/files/3075290/current_meeting_list_41220199095022.pdf)

[tampa-narcotics-anonymous-meeting-list-settings-04-12-2019.json.txt](https://github.com/bmlt-enabled/bread/files/3075291/tampa-narcotics-anonymous-meeting-list-settings-04-12-2019.json.txt)

these do it

sunday 11 am meeting Sunday Simplicity reads Sunday SimpliTampa,

**Comment by pjaudiomv** [comment]
was able to repo, the meeting list was using all the actual field names for bmlt, and not the bread short names. the str_replace needed to move down to work properly

**Comment by pjaudiomv** [comment]
@DanielWright98  you should be able to update and it should work now https://wordpress.org/plugins/bread/

**Comment by radius314** [comment]
delivered in bread 1.9.7 and up

**Comment by DanielWright98** [comment]
Got it. Works like it’s supposed to.

**Comment by pjaudiomv** [comment]
Great glad to hear it. I'm
