### ISSUE TITLE
Error Message After Save

### ISSUE THREAD

**Issue by DanielWright98** [bmlt-enabled/bread#73]
When I save changes in Bread I get this message:

"Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."

Can anyone help with this?

**Comment by radius314** [comment]
Screen shot?

**Comment by DanielWright98** [comment]
<img width="1280" alt="Screen Shot 2019-06-03 at 8 48 55 AM" src="https://user-images.githubusercontent.com/49569781/58803036-8c9e6180-85dc-11e9-8787-d0b8ddf37217.png">

**Comment by radius314** [comment]
Does the hosting provider share some kind of detail as to why mod_security
was triggered?  What version of bread are you running?  Did this start
happening all of a sudden?

**Comment by DanielWright98** [comment]
No notice from host. Bread Version 1.9.8. Happened this morning for the first time.

**Comment by radius314** [comment]
You will need to ask your hosting provider what triggered it.

**Comment by DanielWright98** [comment]
Doing that now.

**Comment by DanielWright98** [comment]
Server, site, files, etc. are working. Host will delist the Mod_Security to fix. Hostgator admins are going to take this so they can fix permanently. Will notify me by email when it's finished.

**Comment by DanielWright98** [comment]
It took three days, but we got this resolved. The Tech Support guy told me he had to delist some white page entries on the back end. Thanks for your help.
