### ISSUE TITLE
No page numbers on booklet

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/bread#75]
Page number not showing up 
beta 1.10.0 and 1.9.8

**Comment by radius314** [comment]
please attach your configuration.

**Comment by californiasteve** [comment]
[mississippi-region-of-narcotics-anonymous-meeting-list-settings-06-05-2019.txt](https://github.com/bmlt-enabled/bread/files/3259117/mississippi-region-of-narcotics-anonymous-meeting-list-settings-06-05-2019.txt)

**Comment by radius314** [comment]
You need to include `[start_page_numbers]` on the Front Page template.  You can do this after `[page_break]`.  I'm going to modify the default template to include this.

**Comment by radius314** [comment]
Actually, it does already, just checked.

**Comment by radius314** [comment]
@californiasteve were you able to see if the above worked?

**Comment by californiasteve** [comment]
Yes, works as expected.
