### ISSUE TITLE
continuation header not working consistently

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#78]
north carolina statewide schedule is a good example of this happening

[nc-region-of-narcotics-anonymous-meeting-list-settings-06-07-2019.json.zip](https://github.com/bmlt-enabled/bread/files/3264247/nc-region-of-narcotics-anonymous-meeting-list-settings-06-07-2019.json.zip)

**Comment by otrok7** [comment]
Is this a bug?  Isn't it just that the "Page Height Adjust" isn't set?  When I set it to -5 everything works.

But really Page Height Adjust is a hacky workaround for a bug, or at least, an unsolved problem:  We don't know if adding a meeting will overflow the column/page until after we write the meeting.  At least, that's how I understand the code.  

But I would offer the user this as a temporary solution.

**Comment by otrok7** [comment]
Fixed in 2.1
